### ISSUE TITLE
Error when building on windows

### ISSUE THREAD

**Issue by AtheMathmo** [sgsellan/botsch-kobbelt-remesher-libigl#12] opened 2022-02-09 09:39 UTC
I'm unable to build the project on windows 10 (64 bit). I can complete the `cmake` command successfully and I see VS Studio projects generated. But when I try to build the projects I run into two errors:

| Severity | Code | Description | Project | File | Line | Suppression State |
| --------- | ----- | ------------- | ------- | ---- | ----- | ------------------- |
| Error | MSB8066 | Custom build for 'C:\me\botsch-kobbelt-remesher-libigl\build\CMakeFiles\12b5f038167ac11694aa035dd46fcc76\pyremesh.module.cpp.rule;C:\me\botsch-kobbelt-remesher-libigl\build\CMakeFiles\12b5f038167ac11694aa035dd46fcc76\bindings.out.cpp.rule;C:\me\botsch-kobbelt-remesher-libigl\CMakeLists.txt' exited with code 9009. | pyremesh | C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets | 242 | |
| Error | LNK1181 | cannot open input file 'Release\remesh.lib' | remeshmesh | C:\Users\jalucas\src\meshopt\ext\botsch-kobbelt-remesher-libigl\build\LINK | 1 | |

FWIW, I wasn't expecting it to build on windows but I got pretty close so I thought I'd share the error in case it is an easy fix.

**Comment by AtheMathmo** [comment] 2022-02-09 09:51
To fix the second error, I made the following changes:

Prefix `__declspec(dllexport)` to all methods declared in the header files of the `src` directory. (I don't think _all_ methods need this). I then had to modify the project properties in VisualStudio so that it exports a static library. Maybe this second step isn't needed if cmake is run over the modified header files.

This enables me to successfully build the executable. But the python library still fails to build with the same error as above.

**Comment by AtheMathmo** [comment] 2022-02-09 14:14
Some hours later, I got it to build.

The first error was because I did not have python tools installed with Visual Studio. I had to hack a bit to get this working (adding my environment python executable to my system path was the only thing that worked in the end). Then pybind11 has a bug that prevents me from building in debug mode. But I got it to build in release mode and now have a .pyd file.

Feel free to close this issue. FWIW, I would suggest adding the `__declspec(dllexport)` prefix to all necessary methods. But other issues I ran into seemed to be environment dependent.

**Comment by sgsellan** [comment] 2022-02-09 14:31
Hi James! Thanks for using our code and for raising this issue. 

Since I am not the one involved with the python bindings, would you be so kind as to add a Pull Request with the changes you think are necessary to run this on Windows, plus instructions in the readme? I can then double check that it works and that way nobody else will have to debug this for hours in the future :)

Have a nice day!

Silvia

**Comment by AtheMathmo** [comment] 2022-02-09 14:57
Sure thing!

I don't have access to a linux system right now (hence the windows installation) so I can't test that these changes are compatible there. I'll put in the PR and rely on you to check that nothing breaks.

Also, as I said above, I'm not sure how much of my debugging was environment-specific. But I am more than happy to include some instructions on how to get the thing building and a troubleshooting guide.

Thanks :)

**Comment by sgsellan** [comment] 2022-02-09 14:58
That would be amazing :) I will count on it and close this issue

**Closed as completed by sgsellan** 2022-02-09 14:58 UTC

**Comment by IcyChlorine** [comment] 2023-06-14 15:53
Can you give a more detailed description on the reason that caused the first problem, as well as how the method you solved it? I've encountered the same problem in Windows, and the problem is still there even after I've added the python executable directory to system path.

My environment: Win 10, python 3.7.2, build use MSVC 2022 x86-64 and in Release Configuration.
